name: "Build"

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  REGISTRY: "ghcr.io"
  USER: "django-files"
  REPO: "docker-nginx"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Get Nginx Version"
        id: nginx
        run: echo "version=$(grep 'ARG NGINX_VERSION=' Dockerfile | cut -d= -f2)" >> $GITHUB_OUTPUT

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: "Docker Login"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and Push"
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.REPO }}:latest
            ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.REPO }}:${{ steps.nginx.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
